
server:
  port: 9999 #服务注册中心端口号
eureka:
  instance:
    hostname: localhost #服务注册中心IP地址
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:9998/eureka/
